### PR TITLE
fix: ensure alias version isn't dropped round-trip

### LINKED ISSUE #6776: Alias version pin is dropped when storage version is v1beta1
### Description

**Observed Behavior**:
When the storage version is v1beta1, the version pin for an alias on a v1 NodePool is dropped. In practice this shouldn't be problematic since version pinning for discovered AMIs isn't supported until v1.0.0 (at which point v1 is the storage version), but this behavior is surprising. 

**Expected Behavior**:
Users should be able to set a version pin on the v1 resource, even when the storage version is v1beta1.

**Versions**:
- Chart Version: 1.0.0
- Kubernetes Version (`kubectl version`): 1.30

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### PR DESCRIPTION
**Pull request by jmdeal**
Fixes #6776 

**Description**
Ensures that the version pin for an alias is maintained via a compatibility annotation applied to the v1beta1 nodeclass.

**How was this change tested?**
`make test`

**Does this change impact docs?**
- [ ] Yes, PR includes docs updates 
- [ ] Yes, issue opened: # 
- [x] No

By submitting this pull request, I confirm that my contribution is made under the terms of the Apache 2.0 license.

### CODE REVIEW

File: pkg/apis/v1/ec2nodeclass_conversion_test.go [hunk 1]
```diff
@@ -121,6 +121,12 @@ var _ = Describe("Convert v1 to v1beta1 EC2NodeClass API", func() {
 			Expect(v1ec2nodeclass.ConvertTo(ctx, v1beta1ec2nodeclass)).To(Succeed())
 			Expect(lo.FromPtr(v1beta1ec2nodeclass.Spec.AMIFamily)).To(Equal(v1beta1.AMIFamilyAL2023))
 		})
+		It("should convert v1 ec2nodeclass alias (pinned)", func() {
+			v1ec2nodeclass.Spec.AMISelectorTerms = []AMISelectorTerm{{Alias: "al2023@v20240807"}}
+			Expect(v1ec2nodeclass.ConvertTo(ctx, v1beta1ec2nodeclass)).To(Succeed())
+			Expect(lo.FromPtr(v1beta1ec2nodeclass.Spec.AMIFamily)).To(Equal(v1beta1.AMIFamilyAL2023))
+			Expect(v1beta1ec2nodeclass.Annotations[AnnotationAliasVersionCompatibilityKey]).To(Equal("v20240807"))
```
Comment (jonathan-innis) [inline pkg/apis/v1/ec2nodeclass_conversion_test.go:128]: HaveKeyWithValue?

**Review by jonathan-innis — DISMISSED** [review]

**Comment by jonathan-innis** [comment]
Might be related to #6792 as well

**Review by jonathan-innis — APPROVED** [review]
LGTM 🚀
