### PR TITLE
chrore: Add CredentialProvider to Bottlerocket settings

### LINKED ISSUE #5507: Bottlerocket: `credential-providers` not configured through userData
### Description

**Observed Behavior**:

Setting `ecr-credential-provider` in `userData` for Bottlerocket is not picked up when using the following configuration:

```
    [settings.host-containers.admin]
    enabled = true
    
    [settings.kubernetes]
    api-server = "https://***.eks.amazonaws.com"
    cluster-certificate = "***"
    cluster-name = "c2-k8s-development"
    
    [settings.kubernetes.node-labels]
    "ecr" = "true"
    
    [settings.aws]
    config = "W3Byb2ZpbGUgZWNyXQpyb2xlX2FybiA9IGFybjphd3M6aWFtOjo8QUNDT1VOVF9JRD46cm9sZS9lY3ItcmVhZC1vbmx5CmNyZWRlbnRpYWxfc291cmNlID0gRWMySW5zdGFuY2VNZXRhZGF0YQo="

    [settings.kubernetes.credential-providers.ecr-credential-provider]
    enabled = true
    image-patterns = ["*.dkr.ecr.*.amazonaws.com"]

    [settings.kubernetes.credential-providers.ecr-credential-provider.environment]
    AWS_PROFILE = "ecr"
```

New instances are spun up but when going into the EC2 instance and requesting the settings using `apiclient`, it returns the following (default?) output:

```
[root@admin]# apiclient get settings.kubernetes.credential-providers
{
  "settings": {
    "kubernetes": {
      "credential-providers": {
        "ecr-credential-provider": {
          "cache-duration": "12h",
          "enabled": true,
          "environment": null,
          "image-patterns": [
            "*.dkr.ecr.*.amazonaws.com",
            "*.dkr.ecr.*.amazonaws.com.cn",
            "*.dkr.ecr-fips.*.amazonaws.com",
            "*.dkr.ecr.us-iso-east-1.c2s.ic.gov",
            "*.dkr.ecr.us-isob-east-1.sc2s.sgov.gov"
          ]
        }
      }
    }
  }
}
```

**Expected Behavior**:

```
[root@admin]# apiclient get settings.kubernetes.credential-providers
{
  "settings": {
    "kubernetes": {
      "credential-providers": {
        "ecr-credential-provider": {
          "cache-duration": "12h",
          "enabled": true,
          "environment": {
            "AWS_PROFILE": "ecr"
          },
          "image-patterns": [
            "*.dkr.ecr.*.amaonaws.com"
          ]
        }
      }
    }
  }
}
```

This output was generated after running the following command:

```
[root@admin]# apiclient set --json '{"settings":{"kubernetes":{"credential-providers":{"ecr-credential-provider":{"enabled":true,"image-patterns":["*.dkr.ecr.*.amaonaws.com"],"environment":{"AWS_PROFILE":"ecr"}}}}}}'
```

**Reproduction Steps** (Please include YAML):

```yaml
---
apiVersion: karpenter.k8s.aws/v1alpha1
kind: AWSNodeTemplate
metadata:
  name: ecr
spec:
  amiFamily: Bottlerocket
  subnetSelector:
    karpenter.sh/discovery: "c2-k8s-development"
  securityGroupSelector:
    karpenter.sh/discovery/k8s-development: "all,k8s-worker,c2-k8s-worker"
  blockDeviceMappings:
    - deviceName: /dev/xvda
      ebs:
        volumeSize: 4Gi
        volumeType: gp3
        encrypted: true
    - deviceName: /dev/xvdb
      ebs:
        volumeSize: 200Gi
        volumeType: gp3
        encrypted: true
  userData: |
    [settings.host-containers.admin]
    enabled = true
    
    [settings.kubernetes]
    api-server = "https://***.eks.amazonaws.com"
    cluster-certificate = "***"
    cluster-name = "c2-k8s-development"
    
    [settings.kubernetes.node-labels]
    "ecr" = "true"
    
    [settings.aws]
    config = "W3Byb2ZpbGUgZWNyXQpyb2xlX2FybiA9IGFybjphd3M6aWFtOjo8QUNDT1VOVF9JRD46cm9sZS9lY3ItcmVhZC1vbmx5CmNyZWRlbnRpYWxfc291cmNlID0gRWMySW5zdGFuY2VNZXRhZGF0YQo="

    [settings.kubernetes.credential-providers.ecr-credential-provider]
    enabled = true
    image-patterns = ["*.dkr.ecr.*.amazonaws.com"]

    [settings.kubernetes.credential-providers.ecr-credential-provider.environment]
    AWS_PROFILE = "ecr"
  tags:
    Name: ecr.c2-k8s-development.us-east-1
    Environment: development
    Role: Kubernetes Node
    Type: ecr
  metadataOptions:
    httpEndpoint: enabled
    httpProtocolIPv6: disabled
    httpPutResponseHopLimit: 1
    httpTokens: required
---
apiVersion: karpenter.sh/v1alpha5
kind: Provisioner
metadata:
  name: ecr
spec:
  providerRef:
    name: ecr
  taints:
    - key: dedicated
      value: ecr
      effect: NoSchedule
  requirements:
    - key: karpenter.k8s.aws/instance-category
      operator: In
      values: ["c"]
    - key: karpenter.k8s.aws/instance-generation
      operator: In
      values: ["4", "5"]
    - key: karpenter.sh/capacity-type # If not included, the webhook for the AWS cloud provider will default to on-demand
      operator: In
      values: ["spot", "on-demand"]
    - key: "karpenter.k8s.aws/instance-cpu"
      operator: In
      values: ["8", "16"]
    - key: ecr
      operator: Exists
  limits:
    resources:
      cpu: "4500"
      memory: 9500Gi
  consolidation:
    enabled: true
```

**Versions**:
- Chart Version: v0.31.2
- Kubernetes Version (`kubectl version`):
```
Client Version: v1.29.0
Kustomize Version: v5.0.4-0.20230601165947-6ce0bf390ce3
Server Version: v1.28.4-eks-8cb36c9
```

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### PR DESCRIPTION
**Pull request by johanvandeweerd**
Fixes #5507

**Description**

This PR adds support for [settings.kubernetes.credential-providers](https://bottlerocket.dev/en/os/1.18.x/api/settings/kubernetes/#credential-providers) for Bottlerocket.

**How was this change tested?**

By building a dev version of Karpenter with the changes of this PR, pushing the image to a private ECR repository and switched the image URL of Karpenter with the dev image on an existing EKS cluster which was already using Karpenter.
When Karpenter was deployed, it spun up a new Bottlerocket instance with the example configuration of [the original issue](https://github.com/aws/karpenter-provider-aws/issues/5507).
After going into the node with SSM I was able to confirm the configuration was updated as expected (which wasn't the case before).

**Does this change impact docs?**
- [ ] Yes, PR includes docs updates 
- [ ] Yes, issue opened: # 
- [x] No

By submitting this pull request, I confirm that my contribution is made under the terms of the Apache 2.0 license.

### CODE REVIEW

File: pkg/providers/amifamily/bootstrap/bottlerocketsettings.go [hunk 1]
```diff
@@ -43,43 +43,54 @@ type BottlerocketSettings struct {
...
 
 type BottlerocketStaticPod struct {
 	Enabled  *bool   `toml:"enabled,omitempty"`
 	Manifest *string `toml:"manifest,omitempty"`
 }
 
+// BottlerocketCredentialProvider is k8s specific configuration for Bottlerocket Kubelet image credential provider
+// https://bottlerocket.dev/en/os/1.18.x/api/settings/kubernetes/#credential-providers
+// https://kubernetes.io/docs/tasks/administer-cluster/kubelet-credential-provider/
+type BottlerocketCredentialProvider struct {
```
Comment (jonathan-innis) [inline pkg/providers/amifamily/bootstrap/bottlerocketsettings.go:87]: Can we also reference the GH link to this schema? e.g. https://github.com/bottlerocket-os/bottlerocket/blob/develop/sources/models/modeled-types/src/kubernetes.rs#L1307

File: pkg/providers/amifamily/bootstrap/bottlerocketsettings.go [hunk 2]
```diff
@@ -43,43 +43,54 @@ type BottlerocketSettings struct {
 
 // BottlerocketKubernetes is k8s specific configuration for bottlerocket api
```
Comment (jonathan-innis) [inline pkg/providers/amifamily/bootstrap/bottlerocketsettings.go:44]: I know that you didn't write the comment on L38 but would you mind updating the comment to point to a valid filepath on BR? That will help us track the schema changes a lot easier. https://github.com/bottlerocket-os/bottlerocket/blob/develop/sources/models/src/lib.rs#L260

**Review by jonathan-innis — COMMENTED** [review]
Nice work! A couple comments on pointers to the BR source code

File: pkg/providers/amifamily/bootstrap/bottlerocketsettings.go (hunk 1 above)
Comment (johanvandeweerd) [reply pkg/providers/amifamily/bootstrap/bottlerocketsettings.go:89]: Done

**Review by jonathan-innis — APPROVED** [review]
LGTM 🚀
