### PR TITLE
fix: Hash volume size quantity value as a string

### LINKED ISSUE #5447: A blockDeviceMapping change in EC2NodeClass does not trigger drift replace
### Description

**Observed Behavior**:

When changing `spec.blockDeviceMapping[0].ebs.volumeSize` no drift replace is triggered. Also, the `karpenter.k8s.aws/ec2nodeclass-hash` annotation remains unchanged.

However, when I flip `spec.detailedMonitoring` a drift replace is triggered. And the `karpenter.k8s.aws/ec2nodeclass-hash` annotation gets updated.

Since the hash value does not get updated for block device mapping changes , I assume the bug is inside the hashing code.

**Expected Behavior**:

Changing `spec.blockDeviceMapping[0].ebs.volumeSize` triggers a drift replace.

**Reproduction Steps** (Please include YAML):

- Create a EC2NodeClass resource and merge in this spec:

```
spec:
  blockDeviceMappings:
  - deviceName: /dev/xvda
    ebs:
      encrypted: true
      volumeSize: 50Gi
      volumeType: gp3
  detailedMonitoring: true
```

- Make note of the `karpenter.k8s.aws/ec2nodeclass-hash` annotation on the EC2NodeClass resource
- Now edit the EC2NodeClass resource and change the volumeSize.
- Check the annotation again. For me the value is unchanged (which is unexpected).

To ensure Karpenter drift does work:

- Edit the EC2NodeClass resource again and flip spec.detailedMonitoring
- Check the annotation. You should see it changed.

**Versions**:
- Chart Version: v0.33.0
- Kubernetes Version (`kubectl version`): v1.27.7

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### PR DESCRIPTION
**Pull request by jonathan-innis**
Fixes #5447

**Description**

This change applies the change that was added in #3330 and ensures that we won't regress on this issue again by adding the relevant testing into functional and E2E testing. Hashing the resource quantity value as a string was missed with the changes were ported over and duplicated from the AWS provider struct in v1alpha1.

**How was this change tested?**

`make presubmit`
`/karpenter snapshot`

**Does this change impact docs?**
- [ ] Yes, PR includes docs updates 
- [ ] Yes, issue opened: # 
- [x] No

By submitting this pull request, I confirm that my contribution is made under the terms of the Apache 2.0 license.

### CODE REVIEW

**Comment by jonathan-innis** [comment]
This change is blocked until we have the ability to version the hashes that we are using to evaluate drift since this would be a breaking change to the existing hash versioning mechanism since a previously unconsidered field would now get hashed with a value.

**Review by jonathan-innis — COMMENTED** [review]
/karpenter snapshot

**Review by jonathan-innis — COMMENTED** [review]
/karpenter snapshot

**Review by jonathan-innis — COMMENTED** [review]
/karpenter snapshot

File: pkg/apis/v1beta1/ec2nodeclass_hash_test.go [hunk 1]
```diff
@@ -66,7 +67,21 @@ var _ = Describe("Hash", func() {
 		Entry("UserData Drift", "588756456110800812", v1beta1.EC2NodeClass{Spec: v1beta1.EC2NodeClassSpec{UserData: aws.String("userdata-test-2")}}),
 		Entry("Tags Drift", "2471764681523766508", v1beta1.EC2NodeClass{Spec: v1beta1.EC2NodeClassSpec{Tags: map[string]string{"keyTag-test-3": "valueTag-test-3"}}}),
 		Entry("MetadataOptions Drift", "11030161632375731908", v1beta1.EC2NodeClass{Spec: v1beta1.EC2NodeClassSpec{MetadataOptions: &v1beta1.MetadataOptions{HTTPEndpoint: aws.String("test-metadata-2")}}}),
-		Entry("BlockDeviceMappings Drift", "436753305915039702", v1beta1.EC2NodeClass{Spec: v1beta1.EC2NodeClassSpec{BlockDeviceMappings: []*v1beta1.BlockDeviceMapping{{DeviceName: aws.String("map-device-test-3")}}}}),
+		Entry("BlockDeviceMappings Drift", "2884646775270747279", v1beta1.EC2NodeClass{Spec: v1beta1.EC2NodeClassSpec{BlockDeviceMappings: []*v1beta1.BlockDeviceMapping{
```
Comment (engedaam) [inline pkg/apis/v1beta1/ec2nodeclass_hash_test.go:70]: I think we should expanded this out make sure that making any changes to every field will cause the cache to change. I don't think this test would have helped us catch the issue we are trying to fix here.

File: test/suites/drift/suite_test.go [hunk 2]
```diff
@@ -680,7 +681,7 @@ var _ = Describe("Drift", func() {
 			{
 				DeviceName: awssdk.String("/dev/xvda"),
 				EBS: &v1beta1.BlockDevice{
-					VolumeSize: resource.NewScaledQuantity(20, resource.Giga),
+					VolumeSize: resources.Quantity("20Gi"),
```
Comment (engedaam) [inline test/suites/drift/suite_test.go:684]: I think we should just test each of these fields separately and this should also eliminate the need to have a separate test just for `volumeSize`

Comment (jonathan-innis) [reply test/suites/drift/suite_test.go:684]: Going to leave this the way it is since it catches a regression specifically on this volumeSize issue which cropped up a couple times only due to the "stringification" piece here. I agree that we should test each field, but I think that we can do so exclusively through the functional testing to avoid extending the time of this E2E too much

File: pkg/apis/v1beta1/ec2nodeclass_hash_test.go (hunk 1 above)
Comment (jonathan-innis) [reply pkg/apis/v1beta1/ec2nodeclass_hash_test.go]: > I don't think this test would have helped us catch the issue we are trying to fix here

Test would have helped catch this specific issue, but I agree that we can expand this out to add additional testing at the field-level.

Comment (jonathan-innis) [reply pkg/apis/v1beta1/ec2nodeclass_hash_test.go]: Updated with the new tests.

File: pkg/apis/v1beta1/ec2nodeclass_hash_test.go [hunk 3]
```diff
@@ -27,76 +28,137 @@ import (
...
+		Entry("MetadataOptions HTTPPutResponseHopLimit", v1beta1.EC2NodeClass{Spec: v1beta1.EC2NodeClassSpec{MetadataOptions: &v1beta1.MetadataOptions{HTTPPutResponseHopLimit: lo.ToPtr(int64(10))}}}),
+		Entry("MetadataOptions HTTPTokens", v1beta1.EC2NodeClass{Spec: v1beta1.EC2NodeClassSpec{MetadataOptions: &v1beta1.MetadataOptions{HTTPTokens: lo.ToPtr("required")}}}),
+		Entry("BlockDeviceMapping DeviceName", v1beta1.EC2NodeClass{Spec: v1beta1.EC2NodeClassSpec{BlockDeviceMappings: []*v1beta1.BlockDeviceMapping{{DeviceName: lo.ToPtr("map-device-test-3")}}}}),
+		Entry("BlockDeviceMapping RootVolume Drift", v1beta1.EC2NodeClass{Spec: v1beta1.EC2NodeClassSpec{BlockDeviceMappings: []*v1beta1.BlockDeviceMapping{{RootVolume: true}}}}),
+		Entry("BlockDeviceMapping DeleteOnTermination Drift", v1beta1.EC2NodeClass{Spec: v1beta1.EC2NodeClassSpec{BlockDeviceMappings: []*v1beta1.BlockDeviceMapping{{EBS: &v1beta1.BlockDevice{DeleteOnTermination: lo.ToPtr(true)}}}}}),
+		Entry("BlockDeviceMapping Encrypted Drift", v1beta1.EC2NodeClass{Spec: v1beta1.EC2NodeClassSpec{BlockDeviceMappings: []*v1beta1.BlockDeviceMapping{{EBS: &v1beta1.BlockDevice{Encrypted: lo.ToPtr(true)}}}}}),
```
Comment (engedaam) [inline pkg/apis/v1beta1/ec2nodeclass_hash_test.go:147]:
```suggestion
		Entry("BlockDeviceMapping Encrypted", v1beta1.EC2NodeClass{Spec: v1beta1.EC2NodeClassSpec{BlockDeviceMappings: []*v1beta1.BlockDeviceMapping{{EBS: &v1beta1.BlockDevice{Encrypted: lo.ToPtr(true)}}}}}),
```
