### PR TITLE
bottlerocket: use default ephemeral storage bind command

### LINKED ISSUE #8393: Setting `instanceStorePolicy: RAID0` with latest Bottlerocket AMI does not include `/var/lib/soci-snapshotter`
### Description

**Observed Behavior**:

When specifying `instanceStorePolicy: RAID0` using the latest release of Bottlerocket (at the moment [v1.44.0](https://github.com/bottlerocket-os/bottlerocket/releases/tag/v1.44.0), which introduced support for soci-snapshotter in kubernetes variants), there is no extra bind dir for `/var/lib/soci-snapshotter`.

**Expected Behavior**:

`instanceStorePolicy: RAID0` includes mounts for all supported directories in Bottlerocket's `ephemeral-storage` command

**Reproduction Steps** (Please include YAML):

```
apiVersion: karpenter.k8s.aws/v1
kind: EC2NodeClass
metadata:
  name: soci-snapshotter-br
spec:
  amiSelectorTerms:
    - alias: bottlerocket@latest
  ...
  blockDeviceMappings:
    - deviceName: /dev/xvda
      ebs:
        volumeSize: 4Gi
        volumeType: gp3
        encrypted: true
    - deviceName: /dev/xvdb
      ebs:
        volumeSize: 100Gi
        volumeType: gp3
        throughput: 600
        encrypted: true
  instanceStorePolicy: RAID0
  userData: |
    [settings.host-containers.admin]
    enabled = true
    [settings.container-runtime]
    snapshotter = "soci"
    [settings.container-runtime-plugins.soci-snapshotter]
    pull-mode = "parallel-pull-unpack"
    [settings.container-runtime-plugins.soci-snapshotter.parallel-pull-unpack]
    max-concurrent-downloads-per-image = 10
    concurrent-download-chunk-size = "16mb"
    max-concurrent-unpacks-per-image = 10
    discard-unpacked-layers = true
```

Then, go to the instance, `lsblk`, observe no mount for soci-snapshotter.

**Versions**:
- Chart Version: latest
- Kubernetes Version (`kubectl version`): 1.33, but this is moot

**Proposed Solution**: 

In order to avoid this situation in the future, where Bottlerocket might add more paths to its [allowlist for `ephemeral-storage` bind dirs](https://github.com/bottlerocket-os/bottlerocket-core-kit/blob/a54c56e11dd357e846a2450d89fdbac6401122a0/sources/api/apiserver/src/server/ephemeral_storage.rs#L295-L314),
1. Bottlerocket will introduce default behavior for `apiclient ephemeral-storage bind` such that if so directories are passed as arguments, all possible directories for the detected platform will be bind mounted (see https://github.com/bottlerocket-os/bottlerocket-core-kit/pull/632)
2. Karpenter will update its implementation to use this default behavior here https://github.com/aws/karpenter-provider-aws/blob/a843836fe85b8e0f82875beacffb68ad226a32a7/pkg/providers/amifamily/bootstrap/bottlerocket.go#L94-L103

**This will be a breaking change for this setting.** Once latest Bottlerocket AMIs have this new default behavior, Karpenter can then ship a version of its chart with the fix. There will be versions of Bottlerocket that do not have this default `ephemeral-storage bind` behavior and thus will not be compatible using `instanceStorePolicy: RAID0` with this version of the Karpenter chart.

---

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### PR DESCRIPTION
**Pull request by ginglis13**
Fixes #8393 

**Description**

Bottlerocket v1.46.0 released with default behavior for the ephemeral-storage bind command. When no arguments are specified, all allowlisted directories for a detected Bottlerocket variant are bind-mounted. This prevents having to consistently update the list of dirs passed as arguments to this command as more are added.

**How was this change tested?**

```
make run
```

Apply nodeclass:

<details>

```
apiVersion: karpenter.k8s.aws/v1
kind: EC2NodeClass
metadata:
  name: default
spec:
  role: "KarpenterNodeRole-fedora-karpenter-demo" # replace with your cluster name
  amiFamily: Bottlerocket
  amiSelectorTerms:
    - alias: bottlerocket@v1.46.0
  instanceStorePolicy: RAID0
  subnetSelectorTerms:
    - tags:
        karpenter.sh/discovery: "fedora-karpenter-demo" # replace with your cluster name
  securityGroupSelectorTerms:
    - tags:
        karpenter.sh/discovery: "fedora-karpenter-demo" # replace with your cluster name
```
</details>

apply nodepool:

<details>

```
apiVersion: karpenter.sh/v1
kind: NodePool
metadata:
  name: default
spec:
  template:
    spec:
      requirements:
        - key: kubernetes.io/arch
          operator: In
          values: ["amd64"]
        - key: kubernetes.io/os
          operator: In
          values: ["linux"]
        - key: karpenter.sh/capacity-type
          operator: In
          values: ["on-demand"]
        - key: karpenter.k8s.aws/instance-category
          operator: In
          values: ["i"]
        - key: karpenter.k8s.aws/instance-family
          operator: In
          values: ["i7ie"]
        - key: karpenter.k8s.aws/instance-generation
          operator: In
          values: ["7"]
      nodeClassRef:
        group: karpenter.k8s.aws
        kind: EC2NodeClass
        name: default
      expireAfter: 720h # 30 * 24h = 720h
  limits:
    cpu: 1000
  disruption:
    consolidationPolicy: WhenEmptyOrUnderutilized
    consolidateAfter: 1m
```

</details>

Apply deployment:

<details>

```
apiVersion: apps/v1
kind: Deployment
metadata:
  name: inflate
spec:
  replicas: 0
  selector:
    matchLabels:
      app: inflate
  template:
    metadata:
      labels:
        app: inflate
    spec:
      terminationGracePeriodSeconds: 0
      securityContext:
        runAsUser: 1000
        runAsGroup: 3000
        fsGroup: 2000
      containers:
      - name: inflate
        image: public.ecr.aws/eks-distro/kubernetes/pause:3.7
        resources:
          requests:
            cpu: 1
        securityContext:
          allowPrivilegeEscalation: false
```

</details>

Observe mounted dirs on provisioned node via `lsblk`:

```
`-nvme0n1p13 259:15   0    1M  0 part
nvme2n1      259:1    0  1.1T  0 disk /var/log/pods
                                      /var/lib/kubelet
                                      /var/lib/containerd
                                      /var/lib/host-containerd
                                      /var/lib/soci-snapshotter
                                      /mnt/.ephemeral
```

repeated above for following `amiSelectorTerms`:

```
  amiSelectorTerms:
    - alias: bottlerocket@v1.45.0
    # - alias: bottlerocket@v1.46.0
    # - alias: bottlerocket@latest
    # - id: ami-045211d4043c5881c # -> bottlerocket-aws-k8s-1.33-x86_64-v1.46.0-431fe75a
    # - id: ami-02fea268d7a3212fd # -> bottlerocket-aws-k8s-1.33-x86_64-v1.45.0-2f4223e5
    # - name: bottlerocket-aws-k8s-1.33-x86_64-v1.46.0-431fe75a
    # - name: bottlerocket-aws-k8s-1.33-x86_64-v1.45.0-2f4223e5
```

**Does this change impact docs?**
- [ ] Yes, PR includes docs updates 
- [ ] Yes, issue opened: # 
- [x] No

By submitting this pull request, I confirm that my contribution is made under the terms of the Apache 2.0 license.

### CODE REVIEW

**Comment by ginglis13** [comment]
^ force push adds support for resolving Bottlerocket AMI version, used to branch which `ephemeral-storage` command is used.

   Implements multi-strategy AMI version resolution from:
    - Alias selectors (bottlerocket@v1.46.0)
    - Name patterns (bottlerocket-aws-k8s-\*-v1.46.0-\*)
    - ID selectors via resolved AMI names
    - Special handling for @ latest (assumes newest version)

**Comment by ginglis13** [comment]
^ force push adjusts the integ test for RAID0 + Bottlerocket

**Comment by ginglis13** [comment]
^ force push converts new test files to ginkgo syntax

File: pkg/providers/amifamily/bootstrap/bottlerocket.go [hunk 1]
```diff
@@ -95,8 +98,17 @@ func (b Bottlerocket) Script() (string, error) {
 		if s.Settings.BootstrapCommands == nil {
 			s.Settings.BootstrapCommands = map[string]BootstrapCommand{}
 		}
+		// Check Bottlerocket version and set appropriate bind command
+		var bindCmd []string
+		// fmt.Println("AMI VERSION", b.AMIVersion)
```
Comment (jmdeal) [inline pkg/providers/amifamily/bootstrap/bottlerocket.go]:
```suggestion
```

File: pkg/providers/amifamily/bootstrap/bottlerocket.go [hunk 2]
```diff
@@ -29,6 +30,8 @@ import (
 
 type Bottlerocket struct {
 	Options
+	AMIVersion       string
+	AMISelectorTerms []v1.AMISelectorTerm
```
Comment (jmdeal) [inline pkg/providers/amifamily/bootstrap/bottlerocket.go]: Any reason we need `AMISelectorTerms` as well as AMI version here?

File: pkg/providers/amifamily/bottlerocket.go [hunk 3]
```diff
@@ -88,9 +88,97 @@ func (b Bottlerocket) UserData(kubeletConfig *v1.KubeletConfiguration, taints []
...
+			continue
+		}
+		if version := extractVersionFromName(ami.Name); version != "" {
+			return version
+		}
+	}
+	return ""
+}
+
+func extractVersionFromName(name string) string {
```
Comment (jmdeal) [inline pkg/providers/amifamily/bottlerocket.go]: nit: I'd scope this to the Bottlerocket object still just so id doesn't pollute the package namespace

```suggestion
func (Bottlerocket) extractVersionFromName(name string) string {
```

File: pkg/providers/amifamily/bootstrap/bottlerocket.go (hunk 2 above)
Comment (ginglis13) [reply pkg/providers/amifamily/bootstrap/bottlerocket.go]: thanks for the catch, remnant of a refactor; I'll remove

**Comment by ginglis13** [comment]
^ force push addresses feedback and lifts version check logic from bootstrap package to amifamily - the `UserData()` method for Bottlerocket now calls `version.SupportsDefaultBind()`

**Review by jmdeal — APPROVED** [review]
LGTM 🚀
