### PR TITLE
fix: Pass security groups and subnets into RunInstances dry-run

### LINKED ISSUE #7834: api error VPCIdNotSpecified: No default VPC for this user
### Description

**Observed Behavior**:

On AWS EKS, I just upgrade karpenter from v1.2.2 to v1.3.0, and the controller logs the following error each minutes (1 line per nodeclass):

```
[pod/karpenter-659b59cc4-tqqm5/controller] {"level":"ERROR","time":"2025-03-04T08:32:01.706Z","logger":"controller","message":"Reconciler error","commit":"ff59416","controller":"nodeclass","controllerGroup":"karpenter.k8s.aws","controllerKind":"EC2NodeClass","EC2NodeClass":{"name":"stable"},"namespace":"","name":"stable","reconcileID":"5d38cd09-d39c-4ef7-a57d-7e2986000246","error":"validating ec2:RunInstances authorization, operation error EC2: RunInstances, https response error StatusCode: 400, RequestID: 3696d466-36c7-4cbf-820d-faeb3639b92c, api error VPCIdNotSpecified: No default VPC for this user. GroupName is only supported for EC2-Classic and default VPC."}
[pod/karpenter-659b59cc4-tqqm5/controller] {"level":"ERROR","time":"2025-03-04T08:32:02.190Z","logger":"controller","message":"Reconciler error","commit":"ff59416","controller":"nodeclass","controllerGroup":"karpenter.k8s.aws","controllerKind":"EC2NodeClass","EC2NodeClass":{"name":"ephemeral"},"namespace":"","name":"ephemeral","reconcileID":"bd5fef0b-e5e5-4de8-b2ff-42660716c633","error":"validating ec2:RunInstances authorization, operation error EC2: RunInstances, https response error StatusCode: 400, RequestID: 9a602b01-0f78-4831-b733-0679646c27d2, api error VPCIdNotSpecified: No default VPC for this user. GroupName is only supported for EC2-Classic and default VPC."}
```

Did I forget to update some IAM permission, or did I miss a tag or something in SG Config ?

**Expected Behavior**:

Controller does not log ERRORs

**Reproduction Steps** (Please include YAML):

**Versions**:
- Chart Version: 1.3.0
- Kubernetes Version (`kubectl version`):
```
Client Version: v1.31.6
Kustomize Version: v5.4.2
Server Version: v1.31.5-eks-8cce635
```

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### PR DESCRIPTION
**Pull request by jonathan-innis**
Fixes #7834

**Description**

Ensure that we model our RunInstances request to look like the launch template that we use for launch with CreateFleet. If we don't specify any details about subnet or security group, EC2 will attempt to validate with the user's default VPC -- if the user doesn't have a default VPC, the request will fail (even if the EKS cluster and subnets that they were attempting to launch into weren't associated with the default VPC)

**How was this change tested?**

`make presubmit`
`/karpenter snapshot`

We deleted the default VPCs from regions in our CI accounts -- this ensures that we are testing the bug that happened here. If tests succeed, that's an indication that this is no longer an issue

**Does this change impact docs?**
- [ ] Yes, PR includes docs updates 
- [ ] Yes, issue opened: # 
- [x] No

By submitting this pull request, I confirm that my contribution is made under the terms of the Apache 2.0 license.

### CODE REVIEW

**Review by jonathan-innis — COMMENTED** [review]
/karpenter snapshot

**Review by jonathan-innis — COMMENTED** [review]
/karpenter snapshot

**Review by jonathan-innis — COMMENTED** [review]
/karpenter snapshot

**Review by jonathan-innis — COMMENTED** [review]
/karpenter snapshot

**Review by jonathan-innis — COMMENTED** [review]
/karpenter snapshot

**Review by jonathan-innis — COMMENTED** [review]
/karpenter snapshot

File: pkg/controllers/nodeclass/validation.go [hunk 1]
```diff
@@ -189,18 +189,26 @@ func (v *Validation) validateRunInstancesAuthorization(
...
+		return "", fmt.Errorf("no resolved security groups in status")
+	}
+	if nodeClass.Status.InstanceProfile == "" {
+		return "", fmt.Errorf("no instance profile in status")
+	}
 
 	var instanceType ec2types.InstanceType
 	requirements := scheduling.NewNodeSelectorRequirements(nodeClass.Status.AMIs[0].Requirements...)
 
+	instanceType = ec2types.InstanceTypeM6gLarge
```
Comment (saurav-agarwalla) [inline pkg/controllers/nodeclass/validation.go:209]: Is this hard-coded because we run this validation before Karpenter runs simulation and determines the instance type?

Not really a blocker for this fix but I wonder what's the downside of this: can we end up blocking customers if say they are at their service quota limit for this instance type (even though Karpenter isn't really going to spin this up)?

Comment (jonathan-innis) [reply pkg/controllers/nodeclass/validation.go:209]: > Maybe I am missing some context here but the RunInstances API considers this field as optional

If you don't specify an instance type and try to use an ARM AMI ID, it will fail because the arch doesn't match

Comment (mikkeloscar) [reply pkg/controllers/nodeclass/validation.go:209]: Sorry for the drive-by comment.. 🙄

What is the actual value of the dry-run call in the first place? Given that it's possible to not cover edge cases as discussed here and seen in #7834 why not simply fail in the actual CreateFleet call?

Does it bring better error messages compared to CreateFleet or what is the motivation?

Comment (jonathan-innis) [reply pkg/controllers/nodeclass/validation.go:209]: Trying it out on my side, it doesn't appear that EC2 does anything smart here -- they basically launch every time with `m1.small` if you don't specify any instance type, which is probably more rare than the m5 we statically coded here

Comment (jonathan-innis) [reply pkg/controllers/nodeclass/validation.go:209]: > it's possible to not cover edge cases as discussed here

I'm not sure that I agree that we can't cover the edge cases. The motivation here is to get a quick and clear error response (and indication on Karpenter objects) that something is wrong with the system
