### PR TITLE
Cache eviction should not throw error if the LT is already deleted

### LINKED ISSUE #5535: Launch template not found error if EC2nodeclass is deleted right after creation.
### Description

**Observed Behavior**: `{"level":"ERROR","time":"2024-01-25T05:33:52.210Z","logger":"controller","message":"failed to delete launch template, InvalidLaunchTemplateId.NotFound: The specified launch template, with template ID lt-019c5be5798f24ca7, does not exist.\n\tstatus code: 400, request id: 86bff5c8-9bc6-485a-a5a8-1619d6c81283","commit":"7cdc79a-dirty","launch-template":"karpenter.k8s.aws/2686062690276844038"}`

**Expected Behavior**: No error should be seen because these Launch Templates were deleted when the EC2NodeClass was deleted which is expected.

**Reproduction Steps** (Please include YAML): 

1. Create an EKS cluster.
2. Install Karpenter
3. Create Nodepool and Nodeclass
4. Delete the Nodeclass immediately after creation

**Versions**:
- Chart Version: v0.33.1
- Kubernetes Version (`kubectl version`): v1.29.0

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### PR DESCRIPTION
**Pull request by jigisha620**
Fixes #5535

**Description**
If we delete EC2NodeClass and there is a cache eviction later, we see errors like these -
`{"level":"ERROR","time":"2024-01-25T05:33:52.210Z","logger":"controller","message":"failed to delete launch template, InvalidLaunchTemplateId.NotFound: The specified launch template, with template ID lt-019c5be5798f24ca7, does not exist.\n\tstatus code: 400, request id: 86bff5c8-9bc6-485a-a5a8-1619d6c81283","commit":"7cdc79a-dirty","launch-template":"karpenter.k8s.aws/2686062690276844038"}`
The change in the PR handles this case by instead printing a debug log that indicates that the LT is already deleted.

**How was this change tested?**
`/karpenter snapshot`

**Does this change impact docs?**
- [ ] Yes, PR includes docs updates 
- [ ] Yes, issue opened: # 
- [x] No

By submitting this pull request, I confirm that my contribution is made under the terms of the Apache 2.0 license.

### CODE REVIEW

**Review by jigisha620 — COMMENTED** [review]
/karpenter snapshot

File: pkg/providers/launchtemplate/launchtemplate.go [hunk 1]
```diff
@@ -370,6 +370,13 @@ func (p *Provider) cachedEvictedFunc(ctx context.Context) func(string, interface
 		}
 		launchTemplate := lt.(*ec2.LaunchTemplate)
 		if _, err := p.ec2api.DeleteLaunchTemplate(&ec2.DeleteLaunchTemplateInput{LaunchTemplateId: launchTemplate.LaunchTemplateId}); err != nil {
+			if awserrors.IsLaunchTemplateNotFound(err) {
+				logging.FromContext(ctx).With(
```
Comment (jonathan-innis) [inline pkg/providers/launchtemplate/launchtemplate.go:374]: No need to log this. Just ignore the error and exit. We have already logged somewhere that we initiated the delete of this launch template already, so adding an additional log to say that we tried again and didn't find it won't really matter to users.

Comment (jonathan-innis) [reply pkg/providers/launchtemplate/launchtemplate.go:374]: If you wanted to, you could directly just call `if awserrors.IgnoreNotFound(err) != nil` as a nice K8s-style syntax for handling this occurcence

**Review by jigisha620 — COMMENTED** [review]
/karpenter snapshot

**Review by jonathan-innis — APPROVED** [review]
Nice work 🎉
