### PR TITLE
fix: Prevent use of launch templates and UserData together

### LINKED ISSUE #2065: Does karpenter support overriding user data when provisioning via an existing launch template?
I am trying to use karpenter to spin up a few powerful bare metal instances for a HPC workload.

For this I would like to override some of bottlerockets settings via the user data toml file.

Does karpenter support overriding the via spec.userData in the AWSNodeTemplate CRD, if we are using an existing launch template via  spec.launchTemplate?

~~~yaml
apiVersion: karpenter.k8s.aws/v1alpha1
kind: AWSNodeTemplate
metadata:
  name: example-node-template
spec:
  launchTemplate: 'example-launch-template'
  subnetSelector:
    kubernetes.io/cluster: example-cluster
  userData: |
    [settings.kubernetes]
    cpu-manager-policy = "static"
~~~

The above config will provision a node, however the cpu-manager-policy is not being set correctly on inspection of bottlerockets config via apiclient get.

I would also like to use settings.boot.kernel-parameters, I have mentioned this missing section of bottlerocket toml on another thread.

**Is an existing page relevant?**

https://karpenter.sh/v0.13.1/aws/launch-templates/#define-launchtemplate-for-provisioner

**What karpenter features are relevant?**

User data for launch templates.

### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### PR DESCRIPTION
**Pull request by suket22**
Fixes #2065

**Description**
If you've specified UserData, we shouldn't be accepting a launchTemplate too.

**How was this change tested?**
* Added a test
* Tested this manually too -

```
for: "provisionerSpecMultiTest.yaml": admission webhook "validation.webhook.provisioners.karpenter.sh" denied the request: validation failed: expected exactly one, got both: spec.launchTemplate, spec.userData
```

**Does this change impact docs?**
- [ ] Yes, PR includes docs updates
- [ ] Yes, issue opened: # 
- [x] No

**Release Note**

```release-note
fix: Prevent use of launch templates and UserData together
```

By submitting this pull request, I confirm that my contribution is made under the terms of the Apache 2.0 license.

### CODE REVIEW

**Review by bwagner5 — APPROVED** [review]
lgtm!

File: pkg/apis/awsnodetemplate/v1alpha1/awsnodetemplate_validation.go [hunk 1]
```diff
@@ -28,5 +33,18 @@ func (a *AWSNodeTemplate) Validate(ctx context.Context) (errs *apis.FieldError)
...
+		a.AWS.Validate(),
+		a.validateUserData(),
+	)
+}
+
+func (a *AWSNodeTemplateSpec) validateUserData() (errs *apis.FieldError) {
+	if a.UserData == nil {
+		return nil
+	}
+	if a.LaunchTemplateName != nil {
```
Comment (ellistarn) [inline pkg/apis/awsnodetemplate/v1alpha1/awsnodetemplate_validation.go:46]: It strikes me that we should simply disallow LaunchTemplateName in AWSNodeTemplate.

Comment (bwagner5) [reply pkg/apis/awsnodetemplate/v1alpha1/awsnodetemplate_validation.go:46]: I don't think we can at this point. It's already released and that would break backwards compatibility.  I realize we could in the confines of semver, but I don't think it's worth it right now and we should just wait for v1alpha6 provisioner and increment the AWSNodeTemplate version at that point.

Comment (suket22) [reply pkg/apis/awsnodetemplate/v1alpha1/awsnodetemplate_validation.go:46]: Discussed this offline, and it's worth considering this during a single version bump (in alignment with whenever we do `v1alpha6`) but let's leave it in until then.

**Review by ellistarn — APPROVED** [review]
