### PR TITLE
fix: don't drift when launched into open ODCR

### LINKED ISSUE #7866: Bug: Nodes marked as drifted despite ReservedCapacity feature gate being disabled by default
### Description

**Observed Behavior**:
1. Even with `ReservedCapacity: false` in Helm values, the `isCapacityReservationDrifted` function in `pkg/cloudprovider/drift.go` still performs capacity reservation drift checks
2. This causes nodes to be marked as drifted if their capacity reservation status doesn't match the EC2NodeClass
3. Results in a continuous loop of node replacements

**Expected Behavior**:
1. When `ReservedCapacity` feature gate is disabled:
   - Capacity reservation drift checks should be skipped entirely
   - Nodes should not be marked as drifted due to capacity reservation mismatches
   - No node replacements should occur due to capacity reservation status

**Reproduction Steps** (Please include YAML):
1. Deploy Karpenter v1.31 with `ReservedCapacity` feature gate disabled or default is `false`
   ```yaml
   settings:
     featureGates:
       reservedCapacity: false
   ```
2. Deploy an EC2NodeClass and NodePool
3. Observe nodes being marked as drifted and replaced continuously

**Technical Details**:
The bug appears to be in the drift detection logic where the feature gate check is missing:

Current implementation in `pkg/cloudprovider/drift.go`:
```go
func isCapacityReservationDrifted(instance *Instance, nodeClass *v1.EC2NodeClass) bool {
    // Performs drift check without checking feature gate
}
```

The function should check the feature gate before performing the drift check:
```go
func isCapacityReservationDrifted(instance *Instance, nodeClass *v1.EC2NodeClass) bool {
    if !v1.CapacityReservationsEnabled {
        return false
    }
    // Rest of the drift check logic
}
```

**Versions**:
- Karpenter Version: v1.31
- Kubernetes Version (`kubectl version`): `Server Version: v1.32.2-eks-bc803b4`
- Installation Method: Helm

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### PR DESCRIPTION
**Pull request by jmdeal**
Fixes #7866 

**Description**
On 1.3.0 and 1.3.1, Karpenter will initiate drift whenever an instance is launched into an open ODCR when the `ReservedCapacity` flag is set to false. This is due to insufficient gating when generating instances, resulting in a capacity reservation label being added to the node / nodeclaim. This then triggers dynamic drift since the reservation is not resolved by the nodeclass.

Note: this should only impact NodeClaims created after an upgrade to v1.3+. NodeClaims created previously won't have the `karpenter.k8s.aws/capacity-reservation-id` label which is responsible for initiating drift.

**How was this change tested?**
- manual testing
- `make test`

**Does this change impact docs?**
- [ ] Yes, PR includes docs updates 
- [ ] Yes, issue opened: # 
- [x] No

By submitting this pull request, I confirm that my contribution is made under the terms of the Apache 2.0 license.

### CODE REVIEW

File: pkg/providers/instance/types.go [hunk 1]
```diff
@@ -40,7 +42,7 @@ type Instance struct {
 	EFAEnabled            bool
 }
 
-func NewInstance(out ec2types.Instance) *Instance {
+func NewInstance(ctx context.Context, out ec2types.Instance) *Instance {
```
Comment (jonathan-innis) [inline pkg/providers/instance/types.go:45]: nit: Maybe worth if we note down why we are using this methodology to block returning back reserved capacity type

File: pkg/cloudprovider/cloudprovider.go [hunk 2]
```diff
@@ -385,7 +385,10 @@ func (c *CloudProvider) instanceToNodeClaim(i *instance.Instance, instanceType *
 
 	if instanceType != nil {
 		for key, req := range instanceType.Requirements {
-			if req.Len() == 1 {
+			// Only add the label if there is a single possible value. Counter examples include zone and reservation id. We need
+			// an explicit check for reservation id because even if there is a single value, if we launched into spot or OD it
+			// won't be used.
+			if req.Len() == 1 && req.Key != cloudprovider.ReservationIDLabel {
```
Comment (jonathan-innis) [inline pkg/cloudprovider/cloudprovider.go:391]: It's not entirely clear to me why this check is here now -- can you help me understand? The comment doesn't make it crystal clear right now IMO

Comment (jonathan-innis) [reply pkg/cloudprovider/cloudprovider.go:391]: Discussed offline: I think this is clear to me but we agreed that we need a generalized approach to solve the offering/instance type requirements problem that this highlights.

We agreed to take a fix to update this comment

**Review by jonathan-innis — APPROVED** [review]
LGTM 🚀
