### PR TITLE
Use strict match with MapToInstanceTypes

### LINKED ISSUE #7925: Capacity cache is never populated with multiple AMIs discovered by bottlerocket alias in amiSelector
### Description

**Observed Behavior**:
Karpenter keeps launching the node that is not able to host a triggering pod

**Expected Behavior**:
Karpenter should learn true instance capacity after first attempt

**Reproduction Steps** (Please include YAML):

nodeclass has the following amiSelector
```yaml
  amiSelectorTerms:
  - alias: bottlerocket@1.32.0-cacc4ce9
```
and discovered amis:
```yaml
  - id: ami-09ede7349be463f40
    name: bottlerocket-aws-k8s-1.30-nvidia-x86_64-v1.32.0-cacc4ce9
    requirements:
    - key: kubernetes.io/arch
      operator: In
      values:
      - amd64
    - key: karpenter.k8s.aws/instance-gpu-count
      operator: Exists
  - id: ami-0de231197f45db6bb
    name: bottlerocket-aws-k8s-1.30-nvidia-aarch64-v1.32.0-cacc4ce9
    requirements:
    - key: kubernetes.io/arch
      operator: In
      values:
      - arm64
    - key: karpenter.k8s.aws/instance-gpu-count
      operator: Exists
  - id: ami-0af46b2a82c2d83fe
    name: bottlerocket-aws-k8s-1.30-x86_64-v1.32.0-cacc4ce9
    requirements:
    - key: kubernetes.io/arch
      operator: In
      values:
      - amd64
    - key: karpenter.k8s.aws/instance-gpu-count
      operator: DoesNotExist
    - key: karpenter.k8s.aws/instance-accelerator-count
      operator: DoesNotExist
  - id: ami-0af46b2a82c2d83fe
    name: bottlerocket-aws-k8s-1.30-x86_64-v1.32.0-cacc4ce9
    requirements:
    - key: kubernetes.io/arch
      operator: In
      values:
      - amd64
    - key: karpenter.k8s.aws/instance-accelerator-count
      operator: Exists
  - id: ami-038cf9675815cb406
    name: bottlerocket-aws-k8s-1.30-aarch64-v1.32.0-cacc4ce9
    requirements:
    - key: kubernetes.io/arch
      operator: In
      values:
      - arm64
    - key: karpenter.k8s.aws/instance-gpu-count
      operator: DoesNotExist
    - key: karpenter.k8s.aws/instance-accelerator-count
      operator: DoesNotExist
```

The capacity cache never gets populated because MapToInstanceTypes only returns first AMI for each instance type. And in this case it's nvidia ami, which never matches

**Versions**:
- Chart Version: v3.3.1
- Kubernetes Version (`kubectl version`): `Client Version: v1.32.3`

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### PR DESCRIPTION
**Pull request by BEvgeniyS**
Fixes #7925

This pull request removes AllowUndefinedWellKnownLabels from the AMI check that and updates the UpdateInstanceTypeCapacityFromNode method to use node instead of nodeclaim for label requirements.

**How was this change tested?**
Added a unit test that verifies capacity updates work correctly when the matching AMI is not first in the NodeClass AMI list

**Does this change impact docs?**
- [x] No

By submitting this pull request, I confirm that my contribution is made under the terms of the Apache 2.0 license.

### CODE REVIEW

File: pkg/controllers/providers/instancetype/capacity/suite_test.go [hunk 1]
```diff
@@ -174,4 +183,303 @@ var _ = Describe("CapacityCache", func() {
 		mem.Sub(resource.MustParse(fmt.Sprintf("%dMi", int64(math.Ceil(float64(mem.Value())*options.FromContext(ctx).VMMemoryOverheadPercent/1024/1024)))))
 		Expect(i.Capacity.Memory().Value()).To(Equal(mem.Value()), "Expected capacity to match VMMemoryOverheadPercent calculation")
 	})
+
+	It("should properly update discovered capacity when matching AMI is first in the list", func() {
```
Comment (jmdeal) [inline pkg/controllers/providers/instancetype/capacity/suite_test.go:187]: I think we can condense these two test cases, along with the previous test. Fundamentally, what we want to verify is that we update the discovered capacity for multiple AMIs, and a change to that AMI results in a cache miss. I could see us structuring a single, unified test something like this:
- For each AMI in the NodeClass' status:
  - List InstanceTypes and find an instance that's compatible with the current AMI
  - Create a Node / NodeClaim for that instance with an updated memory value
  - Reconcile the capacity controller against the created node
  - List instance types and verify that the memory was updated
  - Update the AMI ID for the AMI under test and reapply the NodeClass
  - List instance types again and expect the memory value to return to the original value

I think this captures everything additional you're testing, while condensing our tests. What do you think?

File: pkg/controllers/providers/instancetype/capacity/suite_test.go [hunk 2]
```diff
@@ -136,7 +136,16 @@ var _ = Describe("CapacityCache", func() {
 					Kind:  object.GVK(nodeClass).Kind,
 					Name:  nodeClass.Name,
 				},
-				Requirements: make([]karpv1.NodeSelectorRequirementWithMinValues, 0),
+				// Set up a minimum requirement that is required by the MapToInstanceTypes without allowUndefinedKnownLabels
```
[the remark this answers is not in the document]
Comment (BEvgeniyS) [reply pkg/controllers/providers/instancetype/capacity/suite_test.go:139]: I think we actually have to add it because otherwise it will not pass the requirement on amis. It's a well-known label that is now mandatory

[the remark this answers is not in the document]
Comment (BEvgeniyS) [reply pkg/controllers/providers/instancetype/capacity/suite_test.go:139]: actually, we have to put arch label on the node instead!

File: pkg/controllers/providers/instancetype/capacity/suite_test.go [hunk 3]
```diff
@@ -174,4 +183,303 @@ var _ = Describe("CapacityCache", func() {
...
+				ID:     "subnet-test1",
+				Zone:   "test-zone-1a",
+				ZoneID: "tstz1-1a",
+			},
+			{
+				ID:     "subnet-test2",
+				Zone:   "test-zone-1b",
+				ZoneID: "tstz1-1b",
+			},
+		}
```
[the remark this answers is not in the document]
Comment (BEvgeniyS) [reply pkg/controllers/providers/instancetype/capacity/suite_test.go]: It's because we don't reuse common nodeclaim (we'd have to modify immutable fields for the test to work hence creating a new nodeclaim)

File: pkg/controllers/providers/instancetype/capacity/suite_test.go (hunk 1 above)
Comment (BEvgeniyS) [reply pkg/controllers/providers/instancetype/capacity/suite_test.go:179]: I think it makes total sense, I'll try to merge the test cases

Comment (BEvgeniyS) [reply pkg/controllers/providers/instancetype/capacity/suite_test.go]: I've merged my 2 new cases, but I think there's still a value in having simple 1st test case - depending on which test fails we can understand whether it's ami order problem or something completely different

**Comment by BEvgeniyS** [comment]
Thanks for review @jmdeal!
I've tried to address all the comments, please let me know if there are more changes that would make this better

**Comment by BEvgeniyS** [comment]
Need to dig into 2 failing tests


```
  [FAIL] NodeClass AMI Status Controller Aliases [It] Should resolve all AMIs with correct requirements for Windows2022
  /Users/eugene/src/karpenter-provider-aws/pkg/controllers/nodeclass/ami_test.go:444
  [FAIL] NodeClass AMI Status Controller Aliases [It] Should resolve all AMIs with correct requirements for Windows2019
  /Users/eugene/src/karpenter-provider-aws/pkg/controllers/nodeclass/ami_test.go:409
```

**Comment by BEvgeniyS** [comment]
... I've fixed the test cases here https://github.com/aws/karpenter-provider-aws/pull/7923/commits/31e2476904db709bb439df4771d881a38aafd955

although I have doubts that just adding windows build label is a way to go =(

File: pkg/controllers/nodeclass/validation.go [hunk 4]
```diff
@@ -331,12 +331,20 @@ func (v *Validation) mockOptions(ctx context.Context, nodeClaim *karpv1.NodeClai
 	}
 	return v.amiResolver.Resolve(nodeClass, nodeClaim, []*cloudprovider.InstanceType{
 		{
-			Name:         "m5.large",
-			Requirements: scheduling.NewRequirements(scheduling.NewRequirement(corev1.LabelArchStable, corev1.NodeSelectorOpIn, karpv1.ArchitectureAmd64)),
+			Name: "m5.large",
+			Requirements: scheduling.NewRequirements(
```
Comment (jmdeal) [inline pkg/controllers/nodeclass/validation.go:335]: I don't love that we need to hardcode these requirements here, but I don't think there's a better option since we're hardcoding the instance types used for RunInstances validation. We could fix this by dynamically resolving the instance types from the EC2NodeClass, but I don't think we need to scope that into this PR - I'm actually working on a PR that does that already.

File: pkg/controllers/providers/instancetype/capacity/suite_test.go [hunk 5]
```diff
@@ -174,4 +209,65 @@ var _ = Describe("CapacityCache", func() {
...
+		// Get available instance types from the test environment
+		availableInstanceTypes, err := awsEnv.InstanceTypesProvider.List(ctx, nodeClass)
+		Expect(err).To(BeNil())
+		Expect(availableInstanceTypes).ToNot(BeEmpty(), "No instance types available in test environment")
+
+		// Choose the first instance type for testing
+		testInstanceType := availableInstanceTypes[0]
+		instanceTypeName := testInstanceType.Name
+
+		fmt.Printf("Initial memory capacity for %s: %v\n", testInstanceType.Name, testInstanceType.Capacity.Memory().Value())
```
Comment (jmdeal) [inline pkg/controllers/providers/instancetype/capacity/suite_test.go:227]: I assume this is left over from debugging, we should be good to drop this print now right?

File: pkg/controllers/providers/instancetype/capacity/suite_test.go [hunk 6]
```diff
@@ -174,4 +209,65 @@ var _ = Describe("CapacityCache", func() {
...
+		// Verify that the cache was updated by getting the instance types and checking the memory capacity
+		instanceTypesAfterUpdateReversed, err := awsEnv.InstanceTypesProvider.List(ctx, testNodeClassNvidiaFirst)
+		Expect(err).To(BeNil())
+
+		// Find our instance type and verify its memory capacity was updated
+		found := false
+		for _, it := range instanceTypesAfterUpdateReversed {
+			if it.Name == instanceTypeName {
+				found = true
+				fmt.Printf("Discovered memory capacity for %s: %v\n", it.Name, it.Capacity.Memory().Value())
```
Comment (jmdeal) [inline pkg/controllers/providers/instancetype/capacity/suite_test.go:264]: Same for this print, we generally don't leave prints in the tests and just rely on the expectations to communicate issues.

**Review by jmdeal — COMMENTED** [review]
Only a few small comments, awesome work!

**Comment by jmdeal** [comment]
> That's pretty much the reason I've went with optional parameter approach - I wanted to minimise any side effects like this.

I definitely get this, we generally push back against optional parameters though since you have to reason about whether to include it at every call site. This definitely can make sense (e.g. requirements.Compatible) but I think in this case making it always require all well-known labels made sense.

**Comment by BEvgeniyS** [comment]
Thanks for the review!
I've addressed the comments

**Review by jmdeal — APPROVED** [review]
LGTM 🚀

**Comment by jmdeal** [comment]
Thanks for the contribution!

**Comment by BEvgeniyS** [comment]
Not sure what's the merging routine? Doesn't seem like I can merge it...

**Comment by jmdeal** [comment]
Oh, I didn't realize that. Merged.
