### PR TITLE
fix: discover instances in all available zones

### LINKED ISSUE #5239: Unable to provision nodes in other zone types
I have a requirement to schedule some nodes in a local zone (In this case eu-north-1-cph-1a). I currently have the 1 self managed EKS node running in that zone, and Karpenter successfully starts up. However it cannot provision any new nodes through Karpenter. 

Is there something with my config below that is preventing Karpenter from creating these nodes?

snippet of logs with the error and other startup info:
```
2023-12-05T20:07:33.976Z	DEBUG	controller.nodeclass	discovered subnets	{"commit": "56aaec1", "ec2nodeclass": "company-cluster", "subnets": ["subnet-id (eu-north-1-cph-1a)"]}
2023-12-05T20:07:34.025Z	DEBUG	controller.pricing	updated spot pricing with instance types and offerings	{"commit": "56aaec1", "instance-type-count": 730, "offering-count": 1013}
2023-12-05T20:07:34.135Z	DEBUG	controller.nodeclass	discovered security groups	{"commit": "56aaec1", "ec2nodeclass": "company-cluster", "security-groups": ["sg-id"]}
2023-12-05T20:07:34.189Z	DEBUG	controller.nodeclass	discovered kubernetes version	{"commit": "56aaec1", "ec2nodeclass": "company-cluster", "version": "1.28"}
2023-12-05T20:07:34.625Z	DEBUG	controller.nodeclass	discovered amis	{"commit": "56aaec1", "ec2nodeclass": "company-cluster", "ids": "ami-0bf75e19885e443e6, ami-09389d7cecdb39fba, ami-09389d7cecdb39fba, ami-0f6a90c148c8a59fd", "count": 4}
2023-12-05T20:07:34.730Z	INFO	controller.provisioner	pod kube-system/coredns-d9694c9bb-5758f has a preferred Anti-Affinity which can prevent consolidation	{"commit": "56aaec1"}
2023-12-05T20:07:35.199Z	DEBUG	controller.pricing	updated on-demand pricing	{"commit": "56aaec1", "instance-type-count": 361}
2023-12-05T20:07:35.281Z	DEBUG	controller.disruption	discovered instance types	{"commit": "56aaec1", "count": 361}
2023-12-05T20:07:35.403Z	DEBUG	controller.disruption	discovered offerings for instance types	{"commit": "56aaec1", "instance-type-count": 362}
2023-12-05T20:07:35.451Z	DEBUG	controller.provisioner	discovered availability zones	{"commit": "56aaec1", "zones": ["eu-north-1a", "eu-north-1b", "eu-north-1c"]}
2023-12-05T20:07:35.497Z	DEBUG	controller.provisioner	relaxing soft constraints for pod since it previously failed to schedule, removing: spec.affinity.podAntiAffinity.preferredDuringSchedulingIgnoredDuringExecution[0]={"weight":100,"podAffinityTerm":{"labelSelector":{"matchExpressions":[{"key":"k8s-app","operator":"In","values":["kube-dns"]}]},"topologyKey":"kubernetes.io/hostname"}}	{"commit": "56aaec1", "pod": "kube-system/coredns-d9694c9bb-5758f"}
2023-12-05T20:07:35.515Z	ERROR	controller.provisioner	Could not schedule pod, incompatible with nodepool "company-cluster-default", daemonset overhead={"cpu":"150m","pods":"2"}, no instance type satisfied resources {"cpu":"250m","memory":"70Mi","pods":"3"} and requirements karpenter.sh/capacity-type In [on-demand], karpenter.sh/nodepool In [company-cluster-default], kubernetes.io/arch In [amd64 arm64], kubernetes.io/os In [linux], node.kubernetes.io/instance-type In [m5.2xlarge t3.medium t3.xlarge], topology.kubernetes.io/zone In [eu-north-1-cph-1a], worker/type In [worker] (no instance type met the scheduling requirements or had a required offering)	{"commit": "56aaec1", "pod": "kube-system/coredns-d9694c9bb-5758f"}
```

The current EC2NodeClass I'm using:
```
apiVersion: karpenter.k8s.aws/v1beta1
kind: EC2NodeClass
metadata:
  annotations:
    karpenter.k8s.aws/ec2nodeclass-hash: "16078622133522205464"
  creationTimestamp: "2023-12-05T18:21:13Z"
  finalizers:
  - karpenter.k8s.aws/termination
  generation: 1
  name: company-cluster
  resourceVersion: "206265"
  uid: cfcc70f3-c41c-4b6b-a907-5002f92a5aae
spec:
  amiFamily: AL2
  blockDeviceMappings:
  - deviceName: /dev/xvda
    ebs:
      deleteOnTermination: true
      encrypted: true
      volumeSize: 80Gi
      volumeType: gp2
  instanceProfile: karpenter_node
  metadataOptions:
    httpEndpoint: enabled
    httpProtocolIPv6: disabled
    httpPutResponseHopLimit: 2
    httpTokens: required
  securityGroupSelectorTerms:
  - tags:
      karpenter.sh/discovery: company-cluster
  subnetSelectorTerms:
  - tags:
      karpenter.sh/discovery: company-cluster
status:
  amis:
  - id: ami-0bf75e19885e443e6
    name: amazon-eks-arm64-node-1.28-v20231116
    requirements:
    - key: kubernetes.io/arch
      operator: In
      values:
      - arm64
    - key: karpenter.k8s.aws/instance-gpu-count
      operator: DoesNotExist
    - key: karpenter.k8s.aws/instance-accelerator-count
      operator: DoesNotExist
  - id: ami-09389d7cecdb39fba
    name: amazon-eks-gpu-node-1.28-v20231116
    requirements:
    - key: kubernetes.io/arch
      operator: In
      values:
      - amd64
    - key: karpenter.k8s.aws/instance-gpu-count
      operator: Exists
  - id: ami-09389d7cecdb39fba
    name: amazon-eks-gpu-node-1.28-v20231116
    requirements:
    - key: kubernetes.io/arch
      operator: In
      values:
      - amd64
    - key: karpenter.k8s.aws/instance-accelerator-count
      operator: Exists
  - id: ami-0f6a90c148c8a59fd
    name: amazon-eks-node-1.28-v20231116
    requirements:
    - key: kubernetes.io/arch
      operator: In
      values:
      - amd64
    - key: karpenter.k8s.aws/instance-gpu-count
      operator: DoesNotExist
    - key: karpenter.k8s.aws/instance-accelerator-count
      operator: DoesNotExist
  instanceProfile: karpenter_node
  securityGroups:
  - id: sg-id
    name: company-cluster-node20231204200246985500000001
  subnets:
  - id: subnet-id
    zone: eu-north-1-cph-1a
```

The NodePool
```
apiVersion: karpenter.sh/v1beta1
kind: NodePool
metadata:
  annotations:
    karpenter.sh/nodepool-hash: "3030939166201481529"
  creationTimestamp: "2023-12-05T18:21:14Z"
  generation: 7
  name: company-cluster-default
  resourceVersion: "213646"
  uid: 136e5f9c-9a1e-4626-8954-97f296404582
spec:
  disruption:
    consolidationPolicy: WhenUnderutilized
    expireAfter: 720h
  template:
    metadata:
      labels:
        worker/type: worker
    spec:
      kubelet:
        evictionHard:
          memory.available: 200Mi
      nodeClassRef:
        name: company-cluster
      requirements:
      - key: node.kubernetes.io/instance-type
        operator: In
        values:
        - t3.medium
        - t3.xlarge
        - m5.2xlarge
      - key: karpenter.sh/capacity-type
        operator: In
        values:
        - on-demand
      - key: topology.kubernetes.io/zone
        operator: In
        values:
        - eu-north-1-cph-1a
```

### PR DESCRIPTION
**Pull request by jmdeal**
Fixes #5239 

**Description**
Updates instance type discovery to use zones from the instance type offerings rather than via `DescribeAvailabilityZones`. This maintains a single source of truth for zones while also discovering non-az zones (e.g. local zones).

Note: originally local-zone e2e testing was going to be included here, this is going to be decoupled into a separate PR (coming soon).

**How was this change tested?**
- [x] `make test`
- [x] `/karpenter snapshot`
- [x] test against personal cluster w/ local zones

**Does this change impact docs?**
- [ ] Yes, PR includes docs updates 
- [ ] Yes, issue opened: # 
- [x] No

By submitting this pull request, I confirm that my contribution is made under the terms of the Apache 2.0 license.

### CODE REVIEW

**Review by jmdeal — COMMENTED** [review]
/karpenter snapshot

File: pkg/providers/instancetype/instancetype.go [hunk 1]
```diff
@@ -99,10 +99,7 @@ func (p *Provider) List(ctx context.Context, kc *corev1beta1.KubeletConfiguratio
 		return nil, err
 	}
 	// Get AvailabilityZones from EC2
-	availabilityZones, err := p.getAvailabilityZones(ctx)
-	if err != nil {
-		return nil, err
-	}
+	instanceTypeZones := p.getInstanceTypeZones(ctx, instanceTypeOfferings)
```
Comment (jonathan-innis) [inline pkg/providers/instancetype/instancetype.go:102]:
```suggestion
	zones := p.getInstanceTypeZones(ctx, instanceTypeOfferings)
```

Might just be me, but I find this naming confusing since the function that we call with this data then re-maps this to call it zones and refers to `instanceTypeZones` for something else

File: pkg/providers/instancetype/instancetype.go [hunk 2]
```diff
@@ -175,34 +172,28 @@ func (p *Provider) createOfferings(ctx context.Context, instanceType *ec2.Instan
...
 
-func (p *Provider) getAvailabilityZones(ctx context.Context) (sets.Set[string], error) {
+func (p *Provider) getInstanceTypeZones(ctx context.Context, instanceTypeOfferings map[string]sets.Set[string]) sets.Set[string] {
 	// DO NOT REMOVE THIS LOCK ----------------------------------------------------------------------------
 	// We lock here so that multiple callers to getAvailabilityZones do not result in cache misses and multiple
 	// calls to EC2 when we could have just made one call.
 	// TODO @joinnis: This can be made more efficient by holding a Read lock and only obtaining the Write if not in cache
 	p.mu.Lock()
 	defer p.mu.Unlock()
 	if cached, ok := p.cache.Get(AvailabilityZonesCacheKey); ok {
```
Comment (jonathan-innis) [inline pkg/providers/instancetype/instancetype.go:182]:
```suggestion
	if cached, ok := p.cache.Get(ZonesCacheKey); ok {
```

Should this still be called the `AvailabilityZonesCacheKey` if it isn't representing just AZs?

**Review by jonathan-innis — APPROVED** [review]
LGTM 🚀
