### PR TITLE
Skip instance profile cleanup in isolated VPCs

### LINKED ISSUE #8609: Karpenter 1.7.2 Requires iam:ListInstanceProfiles in Isolated VPCs
### Description

Karpenter 1.7.2 Requires `iam:ListInstanceProfiles` now. In a Isolated VPCs this fails to call the list profiles endpoint as it's not accessible.

### **Observed Behavior**
After upgrading to Karpenter 1.7.2, the controller repeatedly logs errors related to the new *Instance Profile Garbage Collection* feature.  
Even though the `iam:ListInstanceProfiles` permission is included in the IRSA role, the controller still attempts to call the IAM API, which fails in our isolated VPC environment (since there’s no IAM VPC endpoint / NAT gateway etc). Note we explicitly configure our NodeClass with instanceProfile (the name of the role) and have done since version 0.*.

Error:
```
{"level":"ERROR","time":"2025-10-08T21:31:32.281Z","logger":"controller","caller":"controller/controller.go:474","message":"Reconciler error","commit":"afe3eba","controller":"instanceprofile.garbagecollection","namespace":"","name":"","reconcileID":"cfff3f53-41e6-4105-863e-cb8178813af8","aws-operation-name":"ListInstanceProfiles","aws-request-id":"","aws-service-name":"IAM","aws-status-code":0,"error":"listing instance profiles, listing instance profiles, operation error IAM: ListInstanceProfiles, exceeded maximum number of attempts, 3, https response error StatusCode: 0, RequestID: , request send failed, Post \"https://iam.amazonaws.com/\": dial tcp 44.216.198.236:443: i/o timeout"}
```

I think, it appears to be a cosmetic issue... But need someone from AWS/Karpenter to confirm please.

---

### **Expected Behavior**
When a `NodeClass` specifies an `instanceProfile`, Karpenter should:
- Skip IAM API calls for listing instance profiles

Ideally, an optional flag should exist to disable Instance Profile Garbage Collection entirely for isolated environments.

---

### **Reproduction Steps** (Please include YAML)
1. Deploy Karpenter v1.7.2 in an isolated VPC (no internet or IAM endpoint access).  
2. Configure a NodeClass with an explicit instanceProfile.  
3. Observe controller logs.

Example `NodeClass`:
```yaml
apiVersion: karpenter.k8s.aws/v1beta1
kind: NodeClass
metadata:
  name: example
spec:
  instanceProfile: my-managed-instance-profile
  subnetSelectorTerms:
    - tags:
        Environment: isolated
```

---

### **Versions**
- **Karpenter Chart Version:** 1.7.2  
- **Kubernetes Version:** v1.31 (EKS)  

---

*Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request.*

*Please do not leave “+1” or “me too” comments; they generate extra noise for issue followers and do not help prioritize the request.*

*If you are interested in working on this issue or have submitted a pull request, please leave a comment.*

### PR DESCRIPTION
**Pull request by dom-raven**
Fixes #8609 

**Description**
- Skip instance profile cleanup when `options.FromContext(ctx).IsolatedVPC` is true so isolated clusters avoid IAM calls.
- Keep legacy instance profile deletion behind the same guard to prevent failing requests in environments without IAM endpoint access.

**How was this change tested?**
- Not run yet.

**Does this change impact docs?**
- [ ] Yes, PR includes docs updates 
- [ ] Yes, issue opened: # 
- [x] No

By submitting this pull request, I confirm that my contribution is made under the terms of the Apache 2.0 license.

### CODE REVIEW

**Comment by dom-raven** [comment]
It would be good, if folks think this is a viable fix, to backport it to 1.7.*.

**Comment by jigisha620** [comment]
Can you also update the `nodeclass.instanceprofile.garbagecollection` controller to not be appended to the controllers list in case of IsolatedVPC - https://github.com/aws/karpenter-provider-aws/blob/main/pkg/controllers/controllers.go#L95

**Comment by dom-raven** [comment]
> Can you also update the `nodeclass.instanceprofile.garbagecollection` controller to not be appended to the controllers list in case of IsolatedVPC - https://github.com/aws/karpenter-provider-aws/blob/main/pkg/controllers/controllers.go#L95

Good point, added!

File: pkg/controllers/nodeclass/controller.go [hunk 1]
```diff
@@ -193,14 +193,17 @@ func (c *Controller) finalize(ctx context.Context, nodeClass *v1.EC2NodeClass) (
...
-	// Deletes karpenter managed instance profiles for this nodeclass
-	if err := c.cleanupInstanceProfiles(ctx, nodeClass); err != nil {
-		return reconcile.Result{}, err
-	}
-	// Ensure to clean up instance profile that may have been created pre-upgrade
-	legacyProfileName := nodeClass.LegacyInstanceProfileName(options.FromContext(ctx).ClusterName, c.region)
-	if err := c.instanceProfileProvider.Delete(ctx, legacyProfileName); err != nil {
-		return reconcile.Result{}, serrors.Wrap(fmt.Errorf("deleting instance profile, %w", err), "instance-profile", legacyProfileName)
+	// Instance profile cleanup should be skipped in isolated VPCs to avoid IAM calls.
+	if !options.FromContext(ctx).IsolatedVPC {
```
Comment (jigisha620) [inline pkg/controllers/nodeclass/controller.go:197]: Can we also add a test to validate this behavior?

File: pkg/controllers/controllers.go [hunk 2]
```diff
@@ -104,6 +103,9 @@ func NewControllers(
 		crexpiration.NewController(clk, kubeClient, cloudProvider, capacityReservationProvider),
 		metrics.NewController(kubeClient, cloudProvider),
 	}
+	if !options.FromContext(ctx).IsolatedVPC {
```
Comment (jigisha620) [inline pkg/controllers/controllers.go:108]: Can we also add a comment here to convey why we are doing this?

File: pkg/controllers/nodeclass/controller.go (hunk 1 above)
Comment (dom-raven) [reply pkg/controllers/nodeclass/controller.go:197]: I added a new spec that flips the sets isolated VPC mode, deletes a NodeClass, and asserts that no IAM cleanup calls are made while the resource still gets removed.

File: pkg/controllers/nodeclass/suite_test.go [hunk 3]
```diff
@@ -328,4 +328,24 @@ var _ = Describe("NodeClass Termination", func() {
 		Expect(awsEnv.IAMAPI.DeleteInstanceProfileBehavior.Calls()).To(BeZero())
 		Expect(awsEnv.IAMAPI.RemoveRoleFromInstanceProfileBehavior.Calls()).To(BeZero())
 	})
+	It("should skip instance profile cleanup in isolated VPCs", func() {
+		oldCtx := ctx
+		ctx = options.ToContext(ctx, test.Options(test.OptionsFields{IsolatedVPC: lo.ToPtr(true)}))
+		DeferCleanup(func() { ctx = oldCtx })
```
Comment (jigisha620) [inline pkg/controllers/nodeclass/suite_test.go]: While this isn't wrong, can we instead add `ctx = options.ToContext(ctx, test.Options())` in the BeforeEach() after [this](https://github.com/aws/karpenter-provider-aws/blob/9a7a11e84acb1a70febb73f410ce247ec3a258c0/pkg/controllers/nodeclass/suite_test.go#L84) which will take care of reverting it back to the old context? That way if we inject more values into the context in future, BeforeEach() will take care of it.

**Comment by jigisha620** [comment]
Nice work! Will let the CI run.

**Comment by dom-raven** [comment]
@jigisha620 Can we re-run that E2EMatrixTrigger (AMI), it looks unrelated to my code, although correct me if I'm wrong.

**Comment by jigisha620** [comment]
@dom-raven,
I had re-triggered it last night because I saw it failing before. The same tests are failing again. While they mostly look unrelated, it would be good to do a quick check to confirm. Everything else looks good!

**Comment by dom-raven** [comment]
> @dom-raven, I had re-triggered it last night because I saw it failing before. The same tests are failing again. While they mostly look unrelated, it would be good to do a quick check to confirm. Everything else looks good!

I've spent some time looking through the code, I doesn't look related. I also saw that a few commits in main are hitting the same failure, e.g. https://github.com/aws/karpenter-provider-aws/actions/runs/18415250625/job/52477303332

I also wanted to ask, if we merged this could we backport this to 1.7.3 potentially? As this fixes a feature that was released in 1.7.

**Comment by jigisha620** [comment]
@dom-raven,
Thanks for checking. We definitely need to fix them separately.
>I also wanted to ask, if we merged this could we backport this to 1.7.3 potentially? As this fixes a feature that was released in 1.7.

I think it's a fair ask. We can backport this.
Great work btw!

**Comment by mikkoc** [comment]
Can you please release this fix? We're getting the issue in 1.8.2

**Comment by joacoc** [comment]
@mikkoc Yesterday’s release `1.8.3` contains the fix and worked for me.
