### PR TITLE
fix: spurious logging from capacity reservation controller

### LINKED ISSUE #7835: Noisy log after capacity reservations change
### Description

**Observed Behavior**:

When enabling the capacity reservations feature flag, I can see that the following log is fired periodically even though the cluster isn't using capacity reservations

```
{"level":"DEBUG","time":"2025-03-04T09:21:13.495Z","logger":"controller","caller":"singleton/controller.go:26","message":"updated capacity type for nodeclaims","commit":"4e35023","controller":"nodeclaim.capacityreservation","namespace":"","name":"","reconcileID":"273cd6ed-63af-480d-84cf-2dbf964d4c26","NodeClaims":[{"name":"viperberyl-190-edb5qad94b-7zj85"}]}
```

Looking at [the code](https://github.com/aws/karpenter-provider-aws/blob/main/pkg/controllers/nodeclaim/capacityreservation/controller.go#L106), we're incorrectly returning `true` for updated even when no change has been made to the node or to the nodeclaim.

**Expected Behavior**:

We shouldn't see this log fired when there are no changes made to NodeClaims and Nodes, particularly when the NodeClaim isn't even using the `reserved` capacity type.

**Reproduction Steps** (Please include YAML):

1. Create an OD instance with Karpenter
2. Observe this log is fired every minute

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### PR DESCRIPTION
**Pull request by rschalo**
Fixes #7835 

**Description**
Doesn't return true unless a nodeclaim was demoted from Reserved to OnDemand.

**How was this change tested?**
In test cluster

**Does this change impact docs?**
- [ ] Yes, PR includes docs updates 
- [ ] Yes, issue opened: # 
- [x] No

By submitting this pull request, I confirm that my contribution is made under the terms of the Apache 2.0 license.

### CODE REVIEW

File: pkg/controllers/nodeclaim/capacityreservation/controller.go [hunk 1]
```diff
@@ -130,6 +130,7 @@ func (c *Controller) syncCapacityType(ctx context.Context, capacityType string,
 	if err != nil {
 		return false, fmt.Errorf("listing nodes for nodeclaim %q, %w", nc.Name, err)
 	}
+	updated := false
```
Comment (jonathan-innis) [inline pkg/controllers/nodeclaim/capacityreservation/controller.go:133]: Doesn't this miss the case where we just updated for the NodeClaim and not the Node? Pretty minor, but technically incorrect

Comment (jmdeal) [inline pkg/controllers/nodeclaim/capacityreservation/controller.go:133]: We also want to set updated to true if we successfully updated the nodeclaim on line 121, right?

**Review by jonathan-innis — APPROVED** [review]
LGTM 🚀
