### PR TITLE
fix(amifamily) remove HTTPProtocolIPv6 by default for unsupported reg…

### LINKED ISSUE #7081: v0.32.7 Failing MetadataOptions for IPv6 in ISO regions
### Description

**Observed Behavior**:
When using Chart/App version 0.32.7 of Karpenter in ISO AWS regions , the metadataOptions on NodePools is resulting in an error of:
`NodeClaim creating instance with errors: UnsupportedOperation specifying HttpProtocol Metadata Options for an instnace is not support in this region`

We typically provide metadataOptions as
```
{
    http_endpoint = "enabled"
    http_tokens  = "optional"
    httpProtocolIPv6 = "disabled"
    http_put_response_hop_limit = 2         
    instance_metadata_tags  = "disabled"
}  
```
**AWS Communication**
AWS Support verified that IPv6 Metadata is disabled by default in one ISO region, but is not yet a property available in other regions, and therefor, even setting the property to "disabled" or "false" will result in errors as the endpoint/properties do not exist 

**Attempted Troubleshooting**
The following attempted changes were made but none were successful:
- Completely remove any override metadataOptions and allow the chart defaults
```
metadataOptions = {}
```
- Set `httpProtocolIPv6` to `disabled`
```
{
    http_endpoint = "enabled"
    http_tokens  = "optional"
    httpProtocolIPv6 = "disabled"
    http_put_response_hop_limit = 2         
    instance_metadata_tags  = "disabled"
} 
```
- Provide the above standard metadataOptions for all other settings, but remove any setting of `httpProtocolIPv6`
```
{
    http_endpoint = "enabled"
    http_tokens  = "optional"
    ## httpProtocolIPv6 = "disabled"
    http_put_response_hop_limit = 2         
    instance_metadata_tags  = "disabled"
} 
```
- Set `httpProtocolIPv6` to `null`
```
{
    http_endpoint = "enabled"
    http_tokens  = "optional"
    httpProtocolIPv6 = null
    http_put_response_hop_limit = 2         
    instance_metadata_tags  = "disabled"
} 
```

**Workaround**
Reverting all the way back to v0.18.1 works successfully

**Versions**:
- Chart Version: 0.32.7
- Kubernetes Version (`kubectl version`): 1.26.10+rke2r2

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### PR DESCRIPTION
**Pull request by treyrichbourg**
Fixes #7081

**Description**
This PR removes HTTPProtocolIPv6 from default `MetadataOptions` for launch templates in unsupported regions.
Currently consumers are having to address this by using `kubectl patch crd`, creating a kustomization file, or other workarounds. 
All affected regions addressed in this change.
https://github.com/aws/karpenter-provider-aws/issues/5700#issuecomment-1955475202

**How was this change tested?**
- Added new test to `amifamily` suite. 
- All tests passing locally

**Does this change impact docs?**
- [ ] Yes, PR includes docs updates 
- [ ] Yes, issue opened: # 
- [x] No

By submitting this pull request, I confirm that my contribution is made under the terms of the Apache 2.0 license.

### CODE REVIEW

File: pkg/providers/amifamily/resolver.go [hunk 1]
```diff
@@ -230,6 +234,18 @@ func (r DefaultResolver) defaultClusterDNS(opts *Options, kubeletConfig *v1.Kube
...
+	HttpProtocolUnsupported bool
+}{
+	"eu-isoe-west-1":  {HttpProtocolUnsupported: true},
+	"us-iso-east-1":   {HttpProtocolUnsupported: true},
+	"us-iso-west-1":   {HttpProtocolUnsupported: true},
+	"us-isob-east-1":  {HttpProtocolUnsupported: true},
+	"us-isob-west-1":  {HttpProtocolUnsupported: true},
+	"us-isof-south-1": {HttpProtocolUnsupported: true},
+	"us-isof-east-1":  {HttpProtocolUnsupported: true},
+}
```
Comment (jmdeal) [inline pkg/providers/amifamily/resolver.go]: Since `HttpProtocolUnsupported` is `true` for each of these entries, and the existence of the key in the map already implies that it's unsupported can this just be a `sets.Set[string]`?

Comment (treyrichbourg) [reply pkg/providers/amifamily/resolver.go]: Yup. I'll update
