### PR TITLE
fix: only select available AMIs

### LINKED ISSUE #7652: Karpenter picks AMI that is in Pending
### Description

**Observed Behavior**:
1. I created a ec2nodeClass that picks up nodes that are named with `cluster-1-ami-kube-worker-v1.30.8-*`
2. I run a packer build of new AMI (custom node class). When the build is still not complete (last message is `Waiting for AMI to become ready...`), and AMI is in Pending state, the new AMI is picked by Karpenter as the new one.
3. Karpenter detects drift, and creates a new nodeClaim to replace the old "drifted" one

I know I could pin the AMI id, but this would be cumbersome as we rebuild our cluster AMIs frequently. 

**Expected Behavior**:
Karpenter should ignore AMIs that are not in state = Available

**Reproduction Steps** (Please include YAML):
1. Create node class with amiSelector using name (prefix)
2. create nodepool
3. run some test workload to spin at least one node
4. run packer build with matching ami
5. Observe Karpenter logs and behaviour when AMI is in Pending 

**Versions**:
- Chart Version: 1.1.2
- Kubernetes Version (`kubectl version`):
```
Client Version: v1.32.0
Kustomize Version: v5.5.0
Server Version: v1.30.8
```

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### PR DESCRIPTION
**Pull request by jmdeal**
Fixes #7652 

**Description**
Updates the AMI provider to only list AMIs in state `available`.

**How was this change tested?**
`make test` and `/karpenter snapshot`

**Does this change impact docs?**
- [ ] Yes, PR includes docs updates 
- [ ] Yes, issue opened: # 
- [x] No

By submitting this pull request, I confirm that my contribution is made under the terms of the Apache 2.0 license.

### CODE REVIEW

**Review by jmdeal — COMMENTED** [review]
/karpenter snapshot

File: pkg/providers/amifamily/suite_test.go [hunk 1]
```diff
@@ -228,6 +232,45 @@ var _ = Describe("AMIProvider", func() {
...
+				Tags: map[string]string{
+					"test": "test",
+				},
+			}}
+			amis, err := awsEnv.AMIProvider.List(ctx, nodeClass)
+			Expect(err).ToNot(HaveOccurred())
+			Expect(amis).To(HaveLen(1))
+			Expect(amis[0].AmiID).To(Equal("ami-123"))
+		},
+		lo.FilterMap(ec2types.ImageState("").Values(), func(state ec2types.ImageState, _ int) (TableEntry, bool) {
```
Comment (rschalo) [inline pkg/providers/amifamily/suite_test.go:266]: Want to just use Map and continue for available?

**Review by jonathan-innis — APPROVED** [review]
LGTM 🚀

File: pkg/providers/amifamily/suite_test.go (hunk 1 above)
Comment (jmdeal) [reply pkg/providers/amifamily/suite_test.go:266]: That's a little weird because then you have a test named "should ignore images when image.state != available: available". Personally, I prefer it this way.
