### PR TITLE
Fix spurious logging while NodeClass is terminating

### LINKED ISSUE #7850: See a ton of `failed listing instance types for` errors when deleting EC2NodeClass
### Description

**Observed Behavior**:

During the termination of an `EC2NodeClass`, we can see that the disruption controller reacts by throwing a lot of spurious errors for failing to list instance types. We should see if there is either a way to 1) Not return an error like this when we get into this state OR 2) Handle this more gracefully in the disruption controller code so that we don't aggressively log like this under normal operations.

```
{"level":"ERROR","time":"2025-03-06T00:57:24.539Z","logger":"controller","caller":"disruption/helpers.go:147","message":"failed listing instance types for wyrmbush-2-faidzm8t6c","commit":"791df8a","controller":"disruption","namespace":"","name":"","reconcileID":"da55d524-085d-420e-a0e7-cd8df4dbae33","error":"resolving node class, ec2nodeclasses.karpenter.k8s.aws \"jackaliridescent-1-jadothcdhm\" is terminating, treating as not found"}
```

**Expected Behavior**:

We shouldn't log a ton of spurious logs

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### PR DESCRIPTION
**Pull request by jonathan-innis**
Fixes #7850 

**Description**

Treat terminating as NotFound in NodeClass resolution and avoid returning instance types when the NodeClass is terminating or NotFound

**How was this change tested?**

`make presubmit`
`/karpenter snapshot`

**Does this change impact docs?**
- [ ] Yes, PR includes docs updates 
- [ ] Yes, issue opened: # 
- [x] No

By submitting this pull request, I confirm that my contribution is made under the terms of the Apache 2.0 license.

### CODE REVIEW

**Review by jonathan-innis — COMMENTED** [review]
/karpenter snapshot

**Review by jonathan-innis — COMMENTED** [review]
/karpenter snapshot

File: pkg/cloudprovider/cloudprovider.go [hunk 1]
```diff
@@ -181,11 +182,10 @@ func (c *CloudProvider) GetInstanceTypes(ctx context.Context, nodePool *karpv1.N
 	nodeClass, err := c.resolveNodeClassFromNodePool(ctx, nodePool)
 	if err != nil {
 		if errors.IsNotFound(err) {
+			// If we can't resolve the NodeClass, then it's impossible for us to resolve the instance types
 			c.recorder.Publish(cloudproviderevents.NodePoolFailedToResolveNodeClass(nodePool))
+			return nil, nil
 		}
-		// We must return an error here in the event of the node class not being found. Otherwise, users just get
```
Comment (jmdeal) [inline pkg/cloudprovider/cloudprovider.go:186]: Just confirming, we're not concerned about printing this anymore because if the NodeClass is not found, that means the NodePool shouldn't be ready, and we should begin excluding this NodePool from subsequent scheduling simulations anyway?

Comment (jonathan-innis) [reply pkg/cloudprovider/cloudprovider.go:186]: Also, we aren't going to consider NodePools that don't have any instance types (which is how we will represent this here)
