### PR TITLE
fix: Create a separate controller for generating availability/pricing metrics

### LINKED ISSUE #7758: `karpenter_cloudprovider_instance_type_offering_available` is returning the wrong data
### Description

**Observed Behavior**:

The `karpenter_cloudprovider_instance_type_offering_available` should return the offering availability as a global  availability so that we reduce cardinality (and mainly because having a per-NodePool availability doesn't make a ton of sense). Right now, because of [subnet discovery affecting availability](https://github.com/aws/karpenter-provider-aws/blob/main/pkg/providers/instancetype/instancetype.go#L173) through `GetInstanceTypes`, this metric will change as different NodePools call this `GetInstanceTypes` function. 

We need to compute the availability before we filter out offerings due to subnets -- we basically need to just consider the overall offering availability -- removing offerings that are currently stored in our ICE cache

**Expected Behavior**:

`karpenter_cloudprovider_instance_type_offering_available` should return the global offering availability

**Reproduction Steps** (Please include YAML):

- Create two NodePools with different subnet selectors
- Note that the availability metric will oscillate depending on which NodePool is being used to call GetInstanceTypes()

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### PR DESCRIPTION
**Pull request by jonathan-innis**
Fixes #7758

**Description**

This updates our pricing and availability metrics to be generated by a separate controller. This controller polls every minute, pulls all NodePools on the cluster, and unions their results to generate the pricing and availability information globally.

Note that this now means that if no NodePool selects on a specific subnet through their referenced EC2NodeClasses, that  that offering will now report as unavailable. Pricing data should be consistent across NodePools and will continue to be reported regardless if the offering is available or not.

**How was this change tested?**

`make presubmit`
`/karpenter snapshot`

**Does this change impact docs?**
- [ ] Yes, PR includes docs updates 
- [ ] Yes, issue opened: # 
- [x] No

By submitting this pull request, I confirm that my contribution is made under the terms of the Apache 2.0 license.

### CODE REVIEW

**Review by jonathan-innis — COMMENTED** [review]
/karpenter snapshot

**Review by jonathan-innis — COMMENTED** [review]
/karpenter snapshot

File: pkg/fake/pricingapi.go [hunk 1]
```diff
@@ -38,6 +38,7 @@ func (p *PricingAPI) GetProducts(_ context.Context, input *pricing.GetProductsIn
 	return p.GetProductsBehavior.Invoke(input, func(input *pricing.GetProductsInput) (*pricing.GetProductsOutput, error) {
 		// fail if the test doesn't provide specific data which causes our pricing provider to use its static price list
 		return &pricing.GetProductsOutput{}, errors.New("no pricing data provided")
+
```
Comment (rschalo) [inline pkg/fake/pricingapi.go:41]: nit: extra line

File: pkg/fake/cloudprovider.go [hunk 2]
```diff
@@ -93,3 +98,25 @@ func (c *CloudProvider) GetSupportedNodeClasses() []status.Object {
...
+	for _, elem := range defaultDescribeInstanceTypesOutput.InstanceTypes {
+		odPrice[elem.InstanceType] = float64(int64(lo.FromPtr[int32](elem.VCpuInfo.DefaultVCpus)) + lo.FromPtr[int64](elem.MemoryInfo.SizeInMiB))
+		priceList = append(priceList, NewOnDemandPrice(string(elem.InstanceType), odPrice[elem.InstanceType]))
+	}
+	var spotPriceHistory []ec2types.SpotPrice
+	for _, elem := range defaultDescribeInstanceTypeOfferingsOutput.InstanceTypeOfferings {
+		spotPriceHistory = append(spotPriceHistory, ec2types.SpotPrice{
+			InstanceType:     elem.InstanceType,
+			AvailabilityZone: elem.Location,
+			// Model spot pricing as 70% of the spot
```
Comment (rschalo) [inline pkg/fake/cloudprovider.go:116]:
```suggestion
			// Model spot pricing as 70% of OD pricing
```

File: pkg/controllers/metrics/controller.go [hunk 3]
```diff
@@ -0,0 +1,102 @@
...
+				price[dimensions] = offering.Price
+				zones.Insert(offering.Zone())
+			}
+			for zone := range zones {
+				dimensions := metricDimensions{instanceType: instanceType.Name, capacityType: karpv1.CapacityTypeReserved, zone: zone}
+				if _, ok := availability[dimensions]; !ok {
+					availability[dimensions] = false
+					price[dimensions] = 0
+				}
+			}
```
Comment (rschalo) [inline pkg/controllers/metrics/controller.go:76]: So for zones which the NodePool has access to, record an unavailable offering for `CapacityTypeReserved` if it wasn't already set and then make it cost nothing, right? Is this increase in metrics expected for users that don't have this capacity type enabled?

Comment (jonathan-innis) [reply pkg/controllers/metrics/controller.go]: Good catch -- updated this by checking the feature flag

File: pkg/controllers/metrics/suite_test.go [hunk 4]
```diff
@@ -0,0 +1,589 @@
...
+				Group: object.GVK(nodeClass).Group,
+				Kind:  object.GVK(nodeClass).Kind,
+				Name:  nodeClass2.Name,
+			}
+			nodePool3 := coretest.NodePool()
+			nodePool3.Spec.Template.Spec.NodeClassRef = &karpv1.NodeClassReference{
+				Group: object.GVK(nodeClass).Group,
+				Kind:  object.GVK(nodeClass).Kind,
+				Name:  nodeClass3.Name,
+			}
```
Comment (rschalo) [inline pkg/controllers/metrics/suite_test.go:223]: Want to pass `NodeClassReference` directly into `coretest.NodePool()`?

**Review by rschalo — APPROVED** [review]
lgtm
